project: ElementX.xcodeproj
schemes:
- ElementX
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
targets:
- ElementX
# FREE-ACCOUNT: these targets are not built (see project.yml).
# - NSE
# - ShareExtension
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
report_exclude:
  - ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  - ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
retain_swift_ui_previews: true
